config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'users/sign_up' => 'users#index'
  post 'users/sign_up' => 'users#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/static_pages_controller.rb
# frozen_string_literal: true

class StaticPagesController < ApplicationController
  def index; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      flash[:success] = 'Register successfully'
      redirect_to root_path
    else
      flash[:alert] = 'Register failed'
      render :new
    end
  end

  def user_params
    params.require(:user).permit :email, :name, :password, :password_confirmation
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Eshop</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/static_pages/home.html.erb
<h1>HOME</h1>
<p>Hello guy</p>

<p>
  The time is now: <%= Time.now %>
</p>
<%= link_to 'Register', users_sign_up_path %>

app/views/users/index.html.erb
<div class="container">
 <div class="row">
   <h1 class="title">Register</h1>
 </div>
 <div class="row">
   <div class="col-lg-offset-3 col-lg-6">
     <%= form_for :user, url: users_sign_up_path do |f| %>

       <div class="form-group">
         <%= f.label :email %>
         <%= f.email_field :email, placeholder: "Enter your email", class: "form-control" %>
       </div>

       <div class="form-group">
         <%= f.label :fullname %>
         <%= f.text_field :fullname, placeholder: "Enter your fullname", class: "form-control" %>
       </div>

       <div class="form-group">
         <%= f.label :password %>
         <%= f.password_field :password, placeholder: "Enter your password", class: "form-control" %>
       </div>

       <div class="form-group">
         <%= f.label :password_confirmation %>
         <%= f.password_field :password_confirmation, placeholder: "Enter your password_confirmation", class: "form-control" %>
       </div>

       <div class="form-group">
         <%= f.label :avatar %>
         <%= f.file_field :avatar, class:'form-control', placeholder: "Enter image" %>
       </div>

     <div class="text-center">
       <%= f.submit "register", class: "btn btn-info col-lg-12" %>
     </div>
   <% end %>
 </div>
</div>
</div>